version: "3.4"

services:
  bookify.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=PRODUCTION
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
